### ISSUE TITLE
Post ReqBody example?

### ISSUE THREAD

**Issue by Bargsteen** [purescript-hyper/purescript-hypertrout#19]
Hi :)

I've been trying out HyperTrout by following the tutorial and it seems very promising, but now that I want to add a `POST` endpoint that receives as `ReqBody` I've run into trouble. It would be awesome if someone could create or link to a small example using these two concepts in combination.

For example, something like this, where a new entry is saved in a database and it is returned with an ID.

```purescript
type NewEntry = { name :: String }
type Entry = { name :: String, id :: Int }

type API = 
      "entries"        := "entries"  :/ Resource (Get Entries JSON)
      :<|> "newEntry"  := "entries"  :/ ReqBody NewEntry JSON  :> Resource (Post Entry JSON)

entriesResource :: forall m. Monad m => { "GET" :: ExceptT RoutingError m Entries }
entriesResource = { "GET": Entries <$> getEntries }

{- This is the function that I have problems with getting to work -}
newEntryResource :: forall m. Monad m => NewEntry -> { "POST" :: ExceptT RoutingError m Entry }
newEntryResource newEntry = do
  entry <- db.createEntry newEntry
  { "POST": pure entry }                      
```

I hope the example is large enough for you to understand my intentions. Any help would be greatly appreciated 😊

**Comment by nsaunders** [comment]
Hi @Bargsteen, thanks for your interest. Hypertrout does not support `ReqBody` currently, as it is a bit challenging to implement here. [I've attempted it](https://github.com/purescript-hyper/purescript-hypertrout/pull/17), but it's a very hacky solution, which is why it isn't merged.

However, you might be interested in looking at [purescript-nodetrout](https://github.com/nsaunders/purescript-nodetrout).

**Comment by nsaunders** [comment]
Hi @Bargsteen, thanks for your interest. Hypertrout does not support `ReqBody` currently, as it is a bit challenging to implement here. [I've attempted to do so](https://github.com/purescript-hyper/purescript-hypertrout/pull/17), but my solution is very hacky, which is why it isn't merged.

However, you might be interested in taking a look at [Nodetrout](https://github.com/nsaunders/purescript-nodetrout).

**Comment by Bargsteen** [comment]
Hi @nsaunders, ah I see. I'll take a look at Nodetrout, thanks! :)
